/* -- Temporary Table --
permanent table - gets created in any database and remain in db until we drop them But
temporary table - gets created in tempdb ->temporary tables (system database) and automatically deleted.

types :-
1. Local Temporary table - #
	created by using #symbol
	syntex :- 
			create table #Person(
			id nvarchar(20),
			name nvarchar(100)
		)
	Select * from #Person
	drop table #Person
	insert into #Person values ('111','Chitresh')	

	name of this tabel while saving in tempDb ->  tableName	+ underscores (random no.) 
		so why we can check local temporary table in db by :- select * from tempdb..sysobjects where name like '%#Person%'
		hence it is also posible for different connection (query window) to create a multiple temporary table with same name because these tables are distinguished by autogenerated suffixed underscores which are different for every temporary table.
	
	scope :-
		A local temporary table is available for connection (query window) that has created that table. if window is closed or connection is closed, temporary table also gets deleted automatically.
		temporary table created inside stored procedure gets automatically dropped upon completion of execution of stored procedure
	

2. Global Temporary table - ##
	created by  using ##Symbol
	create table ##Person
	(
		id nvarchar(40),
		name nvarchar(100)
	)
	select * from ##Person
	Insert into ##Person values ('111','Chitresh')
	drop table ##Person

	name of this tabel while saving in tempDb not suffixed by any underscores.
		so, there can be only single global temporary table with the a name which is available to all connections. i.e we can't create multiple global tempory table with same name for different users/connections/query window

	Scope :-
		Global temporary table created in any connection (query window) are visible/accessible/available to all other query window (connection). It gets destroyed automatically when all the connection (query windows) closed or the last connection referencing the table is also closed. or sql server is shut down.



*/
--create temporary table
create table #Person(
	id nvarchar(20),
	name nvarchar(100)
)
--selecting records from local temporary table
select * from #Person
--insert records into local temporary table
	insert into #Person values ('111','Chitresh')
--getting name of local temporary table
select * from tempdb..sysobjects where name like '%#Person%'
--drop local temporary table
drop table #Person


--create global temporary table
create table ##Person
	(
		id nvarchar(40),
		name nvarchar(100)
	)
--selecting records from global temporary table
select * from ##Person
--inserting records into global temporary table
insert into ##Person values ('111','Chitresh')
--drop global temporary table
drop table ##person
